language: node_js
node_js:
  - "node"

# script: npm run build
# deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: dist
#  repo: wangdoc/website
#  target_branch: master
#  on:
#    branch: master

branches:
  only:
  - master

script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: bb6a8c216dbe
  - COMMIT_AUTHOR_EMAIL: yifeng.ruan@gmail.com
